### ISSUE TITLE
[FE/UPDATE] Detail Page UI 구현

### ISSUE THREAD

**Issue by hb9901** [B03-group/Ballad-Community#7]
## Description
Detail 페이지 기본 UI 구현 및 라우팅 설정

## To-Do
- [x] Detail 라우팅 설정
- [x] Detail 페이지 및 컴포넌트 파일 생성
- [x] Detail 페이지 UI 구현

## up-to-date
2024.06.02
